### ISSUE TITLE
Use case of selectors

### ISSUE THREAD

**Issue by tokland** [diegohaz/constate#19]
(I was writing some abstractions with the same idea and came across your project, thanks for sharing)

Why do we need selectors? Couldn't we just use a normal function since any state property is available to the render function? `<button onClick={() => increment(1)}>{count} {getParity(count)}</button>`

**Comment by diegohaz** [comment]
Hi, @tokland. 

You can always use external functions. But encapsulating them in containers makes them part of the container's API so they can be used within actions, effects, lifecycle methods and other components using the container.

Take this as an example (this is the biggest container I've written to date): https://github.com/diegohaz/reas/blob/master/src/components/Step/StepContainer.js

If I were to use `hasNext` as an external function, I'd have to import it in `StepContainer` (since I'm using it in the `next` action, for example). If the component using `StepContainer` also needed it, it should do the same. 

`hasNext` only makes sense in the scope of `StepContainer`. Its implementation is very tied to the container state structure. And that's why it should be part of the container's API.

Besides that, I'm planning to memoize selectors inside Constate. This has to be discussed yet. See https://github.com/reduxjs/reselect to learn more.

**Comment by tokland** [comment]
> Its implementation is very tied to the container state structure. And that's why it should be part of the container's API

I hadn't seen the concept of "selectors" before, it really makes sense, thanks for the detailed explanation. 

By the way, your library is very close to what I had in mind, a module to write purely-functional stateful components based on React (no global state, i.e. flux/redux). The only imperative code I see in _constate_ are the `effects` (with its calls to `setState` and, I guess, parent props) and `onXyz` callbacks. In my library, I was return Promises/Rx.Observable's instead, to avoid those side-effects, but I am not still convinced of the results.

**Comment by diegohaz** [comment]
> In my code, I am returning Promise/Rx.Observable instead, to avoid those side-effects

Interesting. Do you have an example of that?

**Comment by tokland** [comment]
Let me put it together and I'll get back to you, I'll be glad to hear your opinion on it.
