### ISSUE TITLE
Reqeust: with(apply)Provider(Container) HOC

### ISSUE THREAD

**Issue by zheeeng** [diegohaz/constate#61]
Hello there, I think we still need a helper HOC for applying the container provider named `withProvider/withContainer/withContainerProvider` or whatever. Otherwise, we always have to modify some component's parent to add such codes `<Container.Provider>....</Container.Provider>` and when we decide to remove a `context` we have to modify its parent again and again.
I have a request that adding the HOC helper:

```javascript
import React, { useState, useContext, useEffect } from "react";
import createContaine, { withProvider }r from "constate";
import {userCounter, MainCounter} from '../containers/counter'
import { Button, Count } from '../components'

// we wish use context inside the DynamicImportedRoutePage(current componet),
// not only its descendants
function DynamicImportedRoutePage() {
   // we may use count context here
  const { increment } = useContext(MainCounter.Context);

    useEffect(
       () => {
           increment()
       },
       []
     )

  return (
    <>
      <Count />
      <Button />
    </>
  );
}

// Use the HOC
export default withProvider(MainCounter)(DynamicImportedRoutePage)
```
When we decide to refactor the `DynamicImportedRoutePage`, just remove/change the HOC and update the function body

**Comment by diegohaz** [comment]
Hey @zheeeng.

I agree that this is annoying. I've also been through that.

But I think this solution could be misleading. One could think that enhancing a component with `withProvider` would allow it to access a sort of container's global state, which obviously doesn't work. I guess it would be really common because people are used to this behavior (redux `connect`, `withTheme` etc.).

In other words, people would just do `withProvider(MainCounter)(Count)` and `withProvider(MainCounter)(Button)` and expect both components share the same state.

**Comment by diegohaz** [comment]
Maybe something like [`recompose#nest`](https://github.com/acdlite/recompose/blob/master/docs/API.md#nest) would be better:
```js
export default nest(MainCounter.Provider, DynamicImportedRoutePage);
```

**Comment by zheeeng** [comment]
React hook is designed as a replacement for recompose, I think.

**Comment by zheeeng** [comment]
I'm from `material-ui`, and its `withTheme` seems clarified ppl that the theme context is derived from the nearest ThemeProvider, not the global theme.

**Comment by diegohaz** [comment]
> I'm from material-ui, and its withTheme seems clarified ppl that the theme context is derived from the nearest ThemeProvider, not the global theme.

Yeah! By "global state" I meant a root Provider as the nearest one. `withSomething` will usually wrap the component with a consumer. But `withProvider` would wrap the component with a new instance of the container's Provider with its own state. That's why I think it might be confusing.

**Comment by diegohaz** [comment]
I've seen that it's really hard for people to understand how React Providers work.

```jsx
import React, { useState } from "react";
import createContainer from "constate";

function useCounter({ initialCount = 0 }) {
  const [count, setCount] = useState(initialCount);
  const increment = () => setCount(count + 1);
  return { count, increment };
}

const CounterContainer = createContainer(useCounter);

function App() {
  return (
    <CounterContainer.Provider initialCount={2}>
      <Foo />
    </CounterContainer.Provider>
    <CounterContainer.Provider initialCount={10}>
      <Bar />
    </CounterContainer.Provider>
  );  
}
```

In the example above, `Foo` and `Bar` will access different states even though they have the same shape (`{ count, increment }`). Calling `increment` from `Foo` will have no effect on the state consumed by `Bar`.

Note: I'm not saying that you don't understand that. I'm just leaving it here because I know people will come to this issue with this confusion.

**Comment by diegohaz** [comment]
For now, you can just create an utility function in your app:
```jsx
const nest = (...components) => props =>
  components.reduceRight(
    (children, Current) => <Current {...props}>{children}</Current>,
    props.children
  );
```

I'm gonna use this too.

**Comment by awmleer** [comment]
Maybe this package can help: [with-wrapper](https://github.com/awmleer/with-wrapper)

**Comment by diegohaz** [comment]
Closing this issue as there are enough alternatives. I recommend this one: https://github.com/diegohaz/constate/issues/61#issuecomment-447558713
