### ISSUE TITLE
minor feedback

### ISSUE THREAD

**Issue by alidcastano** [diegohaz/constate#62]
(following up on your tweet)

to simplify things further, I'd say that the `Container` terminology is unnecessary and the API would be nicer if it aligned with React's default context/hook API

so have `createContext` (rather than `createContainer`) return `{ Provider, Consumer}`, and pass it to the hook as `useContext(MyContext)` 

in other words, constate is just a tiny wrapper around context to faciliate usage n improve performance without a custom API (at least this I'm thinking of doing in my app, using your code as an example, so thanks!)

**Comment by alidcastano** [comment]
trying this out now and the above might not actually work if `Provider` passed to `useContext` has to be React's Provider... but maybe there's a way to work around that so I'll leave this issue open

**Comment by alidcastano** [comment]
yea playing around with this, doesn't seem like mimicking their API would be the ideal solution (I'm guessing you might have tried this first as well, haha), closing this!

**Comment by diegohaz** [comment]
Yeah, that was my first try haha. It turns out that the React Context object has lots of hidden properties and, even though I could reproduce them (like setting `$$typeof: Symbol("react.context")`), it could break on any patch/minor version of React. 

Besides that, `createContext` with a different API could be confusing.

Anyway, thanks for the feedback. I really appreciate that. :)
