### ISSUE TITLE
Move type declarations to root dir

### ISSUE THREAD

**Issue by ingver** [diegohaz/constate#74]
In current version (1.0.0) type declarations are published under `dist/ts/src` and when importing for example by the default VS Code action, the result is:

![image](https://user-images.githubusercontent.com/13944414/55175131-8afd8b00-51a0-11e9-9456-785f6580e53d.png)

Besides unfancy look, it leads to error during compilation
```
Module not found: Error: Can't resolve 'constate/dist/ts/src' in 'C:\source\project\src'
...
```

**Comment by diegohaz** [comment]
That's a bug in VSCode/IntelliSense, isn't it?

**Comment by ingver** [comment]
> That's a bug in VSCode/IntelliSense, isn't it?

Not sure. Should it work another way? If `.d.ts` file is in `/dist/ts/src`, why should it point to `/`?

> Does it work if you manually remove `/dist/ts/src`?

Yep, it works. But I must manually write import or edit every auto-import statement.

**Comment by diegohaz** [comment]
> If .d.ts file is in /dist/ts/src, why should it point to /?

Honestly, I'm not sure how VSCode parses it, but the `types` field in package.json is pointing to `dist/ts/src`:
https://github.com/diegohaz/constate/blob/1889be89d51bbc72ff1ebf2b621d402b71bb2ea4/package.json#L11

That should be enough to VSCode understand it. That's why I think it's a bug in VSCode.
